import { createAgentFailureNotifier } from '../../core/agent/agentErrors'
import type { CreateExecutionNodesDeps } from './types'

export function createExecContext(deps: CreateExecutionNodesDeps) {
  const {
    ensureNotAborted,
    opts,
    policyPromise,
    defaultPolicy,
    lastUserText,
    hasStrongDbAnchor,
    callDbAgent,
    appendMetrics,
    isDbNoData,
    emitTrace,
    summarize,
    deriveScenarioKey,
    callRagAgent,
    ragEvidenceFromProbe,
    probeRagEvidence,
    parseRagClarifyPayload,
    mergeTaskPlan,
    getEffectivePlanSteps,
    mergeMeta,
    callCodeAgent,
    callAiAdminAgent,
    callCrawlerAgent,
    callLobsterAgent,
    parseCrawlerClarifyPayload,
    crawlerTaskPlanPatch,
    runInternalAgent,
    filterCrawlerResultDomestic,
    callMultimodalAgent,
    callMusicAgent,
    callVideoAgent,
    ragRelevanceJudge,
    ragEvidenceMatchJudge,
    ragScopeHintJudge,
    llmInvoke
  } = deps
  const notifyAgentFailure = createAgentFailureNotifier(opts.sendEvent, opts.runId)
  return {
    ensureNotAborted,
    opts,
    policyPromise,
    defaultPolicy,
    lastUserText,
    hasStrongDbAnchor,
    callDbAgent,
    appendMetrics,
    isDbNoData,
    emitTrace,
    summarize,
    deriveScenarioKey,
    callRagAgent,
    ragEvidenceFromProbe,
    probeRagEvidence,
    parseRagClarifyPayload,
    mergeTaskPlan,
    getEffectivePlanSteps,
    mergeMeta,
    callCodeAgent,
    callAiAdminAgent,
    callCrawlerAgent,
    callLobsterAgent,
    parseCrawlerClarifyPayload,
    crawlerTaskPlanPatch,
    runInternalAgent,
    filterCrawlerResultDomestic,
    callMultimodalAgent,
    callMusicAgent,
    callVideoAgent,
    ragRelevanceJudge,
    ragEvidenceMatchJudge,
    ragScopeHintJudge,
    llmInvoke,
    notifyAgentFailure
  }
}

export type ExecContext = ReturnType<typeof createExecContext>
